name: Python application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --cov=.

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # Добавьте другие переменные среды, если необходимо
        
        with:
          # Добавьте аргументы, как указано в вашем предыдущем сообщении
          args: >
            -Dsonar.projectKey=Gygygnom_PO
            -Dsonar.organization=gygygnom
            -Dsonar.sources=./PO
            -Dsonar.exclusions=**/*,./PO/**/*
            -Dsonar.tests=./
            -Dsonar.test.inclusions=**/test_game.py
            -Dsonar.python.coverage.reportPaths=./coverage.xml
